### PR TITLE
[FLAP-141] Fixed concurrent map write bug

### PR DESCRIPTION
**Pull request by obonobo**
# Description

The SimulatorService implementation uses a map to keep track of running
Simulations, but we had neglected to synchronize the map hence the bug.

To fix, added a sync.Mutex to the SimulatorService struct. Any methods that
access the map will lock on that mutex first.

## Link to work item

Closes FLAP-141

## How to Test

For @iggcomp reviewing: also try out this branch with the JMeter suite

To test out the changes, I've included a mini load testing script that can be
run:

```bash
# Spin up the app
make
./app

# In another terminal, run the load tester script - you won't encounter any
# concurrent map write errors. If you try this script on the commit prior to
# this PR, you will get concurrent map write errors at n > 1000
go run scripts/simple_load_tester.go -times 10000
```

### CODE REVIEW

**Review by instamine — APPROVED** [review]
Issue debugged, code looks fine.

**Comment by obonobo** [comment]
@iggcomp I'll need your approval before merging since this bug is a blocker for your JMeter perf testing

**Comment by iggcomp** [comment]
I'm still getting connection refused responses when I run jmeter tests on this branch and crashes the runtime when running load/stress tests

**Comment by iggcomp** [comment]
error was on my end I was improperly rebuilding the app

**Comment by iggcomp** [comment]
for windows the app requires to be made as an EXE, @obonobo may I add a commit to this branch that updates the readme to have a subsection for windows specifying that the app must be built as app.exe

**Comment by obonobo** [comment]
@iggcomp, yes please add a commit on top of this PR with your README.md changes.

Make sure your message follows the format:

```plaintext
What you changed

...explanation...

Related FLAP-141
```

**Review by iggcomp — APPROVED** [review]
run jmeter tests and tests scripts with this branch and am no longer experiencing concurrent map writes! also added to the readme to clarify build instructions on windows

**Comment by obonobo** [comment]
Cool, ty @iggcomp. Leave a review to approve

**Pull request merged**
